plugins {
    id 'net.fabricmc.fabric-loom'
    id 'lazycraft.loader'
}

def commonBuildOutput = rootProject.layout.projectDirectory.dir('common/build')

loom {
    splitEnvironmentSourceSets()

    SourceSetContainer commonSourceSets = rootProject.project(':common')
            .extensions.getByType(SourceSetContainer)
    SourceSetContainer fabricSourceSets = project.extensions.getByType(SourceSetContainer)
    def commonMainSourceSet = commonSourceSets.named(SourceSet.MAIN_SOURCE_SET_NAME)
    def fabricMainSourceSet = fabricSourceSets.named(SourceSet.MAIN_SOURCE_SET_NAME)
    def fabricClientSourceSet = fabricSourceSets.named('client')

    runs {
        client {
            client()
            displayName.set('Fabric Client')
            generateRunConfig.set(true)
            runDirectory.set(project.layout.projectDirectory.dir('runs/client'))
        }
        server {
            server()
            displayName.set('Fabric Server')
            generateRunConfig.set(true)
            runDirectory.set(project.layout.projectDirectory.dir('runs/server'))
        }
    }

    mods {
        lazycraft {
            sourceSet commonMainSourceSet.get()
            sourceSet fabricMainSourceSet.get()
            sourceSet fabricClientSourceSet.get()
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    clientCompileOnly project(':common')
    compileOnly project(':common')
    clientRuntimeOnly files(
            commonBuildOutput.dir('classes/java/main'),
            commonBuildOutput.dir('resources/main')
    )
    clientCompileOnly "maven.modrinth:9s6osm5g:${cloth_config_fabric_version}" // Cloth Config API
    clientCompileOnly 'maven.modrinth:mOgUt4GM:njXb639R' // Mod Menu
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

tasks.named('sourcesJar', Jar) {
    from sourceSets.client.allSource
}
