plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}" apply false
    // The common module uses NeoForm to compile loader-neutral Minecraft code.
    id 'net.neoforged.moddev' version "${mdg_version}" apply false
}

allprojects {
    group = project.maven_group
    version = project.mod_version

    repositories {
        exclusiveContent {
            forRepository {
                maven {
                    name = 'Modrinth'
                    url = 'https://api.modrinth.com/maven'
                }
            }
            filter {
                includeGroup 'maven.modrinth'
            }
        }
    }
}
