# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false
# Java and project properties
java_version=25
mod_id=lazycraft
mod_name=LazyCraft
mod_author=GoldOliverK09
mod_version=1.3.2
maven_group=klumpler.lazycraft
license=MIT
description=A collection of quality-of-life crafting features to make crafting feel intuitive
#minecraft_version=26.2
minecraft_version=26.1
minecraft_version_range=>=26.1 <26.3
minecraft_version_readable=26.x.x
#neo_form_version=26.2-1
neo_form_version=26.1-1
mdg_version=2.0.141

# Fabric properties: check https://fabricmc.net/develop when updating Minecraft.
loader_version=0.19.0
loom_version=1.17-SNAPSHOT
#fabric_api_version=0.158.0+26.2
fabric_api_version=0.155.2+26.1.2

# NeoForge properties: check https://projects.neoforged.net/neoforged/neoforge when updating Minecraft.
#neoforge_version=26.2.0.63
neoforge_version=26.1.2.97
neoforge_version_range=[26.1.2.97,26.3)
neoforge_loader_version_range=[4,)
neoforge_minecraft_version_range=[26.1,26.3)
# Optional client configuration UI, one artifact per loader.
cloth_config_fabric_version=Nv3xnWXd
cloth_config_neoforge_version=TimoYzse
