plugins {
    id 'lazycraft.common'
}

configurations {
    commonJava {
        canBeResolved = true
    }
    commonResources {
        canBeResolved = true
    }
}

dependencies {
    commonJava(project(path: ':common', configuration: 'commonJava'))
    commonResources(project(path: ':common', configuration: 'commonResources'))
}

tasks.named('jar', Jar) {
    dependsOn(project(':common').tasks.named('classes'))
    from(project(':common').sourceSets.main.output)
}

tasks.named('sourcesJar', Jar) {
    dependsOn(configurations.commonJava)
    from(configurations.commonJava)
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}
